### PR TITLE
Fix comments which start with non-alphanumerics

### LINKED ISSUE #7: Doc-comments are not recognized as comments
What the title says

image

### PR DESCRIPTION
**Pull request by postsolar**
Closes #7.

Comments get parsed incorrectly if they start with some symbols, e.g. `.` or `#` or `|`, but not `;` or `,`. This commit makes everything starting with `--` into a comment.
Just in case, it can't break any infix operator because no operator in PureScript can contain `--`.

I've never before touched C so I'd be thankful for edits suggestions.

### CODE REVIEW

File: src/scanner.c [hunk 1]
```diff
@@ -602,8 +602,7 @@ static Symbolic s_symop(wchar_vec s, State *state) {
       default: return con_or_var(c);
     }
   } else {
-    bool is_comment = true;
-    for (size_t i = 0; i < s.len; i++) { is_comment &= s.data[i] == '-'; }
+    bool is_comment = (s.data[0] == '-') & (s.data[1] == '-');
```
Comment (Maskhjarna) [inline src/scanner.c:605]: I'd bet the compiler does some magic here anyways so I doubt it matters, but double ampersand prevents the RHS expression from being evaluated if the LHS is false.

**Review by Maskhjarna — APPROVED** [review]
